@startuml
!define RECTANGLE class

' Generate using:

' java -jar /home/minguzzi/download/plantUML/plantuml-1.2025.2.jar -o${REPO_ROOT}/docs/tech_kb_project/uml_schemas ${REPO_ROOT}/docs/tech_kb_project/storage.puml

title Tech KB Doc


package storage
{

class Embedding
note right of Embedding
  list[ numbers]
end note

abstract class Embedder
{
  {abstract} int embeddingSize()
  {abstract} Embedding embedDocument( [str] )
}

class EmbedderFactory
{
  {static} createEmbedder()
}


}
' package storage

@enduml
